### ISSUE TITLE
Cursor issue in the chat interface

### ISSUE THREAD

**Issue by cyh76507707** [ggomaeng/chatcasso#4]
채팅창에 문장 중간에 뭐 추가/변경하려고 하면 커서가 자동으로 맨 뒤로 가는 이슈 있음.

**Comment by cyh76507707** [comment]
한글 안쳐지는건 맥북 이슌가?
![Screenshot 2022-12-19 at 3 26 42 AM](https://user-images.githubusercontent.com/15100667/208313215-4f04fc33-49f9-4d54-97a5-3be34dafc68c.png)

**Comment by sydneyitguy** [comment]
Fixed #2
